# Generated by Django 4.0.3 on 2022-04-14 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_title', models.TextField(max_length=500, verbose_name='Наименование')),
                ('element_dimension', models.CharField(blank=True, max_length=500, null=True)),
                ('element_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=500)),
                ('product_fabrication', models.IntegerField()),
                ('product_standard', models.IntegerField()),
                ('product_note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(max_length=200)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.element')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='elements',
            field=models.ManyToManyField(through='product.Product_Element', to='product.element'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_type'),
        ),
    ]
